# John Hardy
# FisherPrice example - Create user "fisherprice" and memberof "EvmGroup-users" in CloudForms.
---
- hosts: localhost
  vars_files: 
    - secret.yaml
  tasks:
    - name: Gather EC2 instances facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
      register: info

    - debug: var=info
