# Swapnil Dahiphale
# List AWS instances example
---
- hosts: localhost
  vars_files: 
    - secret.yaml
  tasks:
    - name: Gather EC2 instances facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "us-east-1"
      register: info

    - debug: var=info
